@base_url = http://localhost:8080


### Create a contact
POST {{base_url}}/api/contacts
Content-Type: application/json

{
  "first_name": "John",
  "last_name": "Doe",
  "email": "john1@codersgyan.com",
  "tags": [
    { "text": "waitlist:golang" }
  ]
}